// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWQzRcbeTnMIyLLwTlQwDsauxzWvJUYqw',
    appId: '1:286799340423:web:7faef80b17ddaeaacba922',
    messagingSenderId: '286799340423',
    projectId: 'axiipsic-test',
    authDomain: 'axiipsic-test.firebaseapp.com',
    storageBucket: 'axiipsic-test.appspot.com',
    measurementId: 'G-NQXTK1EH3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRMRl68L6XW4hwnu3vo-3iXOciEwMQjbI',
    appId: '1:286799340423:android:3fbc68892ec5f0c1cba922',
    messagingSenderId: '286799340423',
    projectId: 'axiipsic-test',
    storageBucket: 'axiipsic-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbdGQuS4n89zg9L1020rLsnCXkFAtB-6A',
    appId: '1:286799340423:ios:e661f2c5a335b614cba922',
    messagingSenderId: '286799340423',
    projectId: 'axiipsic-test',
    storageBucket: 'axiipsic-test.appspot.com',
    iosClientId: '286799340423-6cp22og670i9ltc975igh6nmfa4jcufd.apps.googleusercontent.com',
    iosBundleId: 'com.example.axiipsicTt2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbdGQuS4n89zg9L1020rLsnCXkFAtB-6A',
    appId: '1:286799340423:ios:e661f2c5a335b614cba922',
    messagingSenderId: '286799340423',
    projectId: 'axiipsic-test',
    storageBucket: 'axiipsic-test.appspot.com',
    iosClientId: '286799340423-6cp22og670i9ltc975igh6nmfa4jcufd.apps.googleusercontent.com',
    iosBundleId: 'com.example.axiipsicTt2',
  );
}
