// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqK_GOEGCqqSTbJHjp7ZQ6qXTaLOe44lo',
    appId: '1:318337389121:web:e936e3164b4976585aacc0',
    messagingSenderId: '318337389121',
    projectId: 'proyectofinalcgyt',
    authDomain: 'proyectofinalcgyt.firebaseapp.com',
    storageBucket: 'proyectofinalcgyt.appspot.com',
    measurementId: 'G-QYRCLRKEZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdCQQsmPm765VEMyRpOxmknMzMXtEbW-A',
    appId: '1:318337389121:android:3c94c24a50a7bea95aacc0',
    messagingSenderId: '318337389121',
    projectId: 'proyectofinalcgyt',
    storageBucket: 'proyectofinalcgyt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBejSQjZWTCIxXDR1MyFN0ERu51BpnSyeU',
    appId: '1:318337389121:ios:b386abf2b04245e15aacc0',
    messagingSenderId: '318337389121',
    projectId: 'proyectofinalcgyt',
    storageBucket: 'proyectofinalcgyt.appspot.com',
    androidClientId: '318337389121-vce2d4udh4iusn89sdt531a1f1if7voc.apps.googleusercontent.com',
    iosClientId: '318337389121-g6m0jrj8ipaa39pp2tskuvu32rmt3gsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.axiipsicTt2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBejSQjZWTCIxXDR1MyFN0ERu51BpnSyeU',
    appId: '1:318337389121:ios:b386abf2b04245e15aacc0',
    messagingSenderId: '318337389121',
    projectId: 'proyectofinalcgyt',
    storageBucket: 'proyectofinalcgyt.appspot.com',
    androidClientId: '318337389121-vce2d4udh4iusn89sdt531a1f1if7voc.apps.googleusercontent.com',
    iosClientId: '318337389121-g6m0jrj8ipaa39pp2tskuvu32rmt3gsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.axiipsicTt2',
  );
}
